### ISSUE TITLE
Every auth0-php classes are final and should not be declared as lazy services

### ISSUE THREAD

**Issue by amenophis** [Happyr/auth0-bundle#42]
Hi @Nyholm,
I encounter an issue when trying this bundle, in auth0-php@8.0.0-BETA1, every classes are final.
In my project, I got the `symfony/proxy-manager-bridge` component installed. As you declared services as lazy in the configuration, it ends up with the following error:
`ProxyManager\Exception\InvalidProxiedClassException: Provided class "Auth0\SDK\API\Authentication" is final and cannot be proxied`

Do you think we can simply remove the lazy services configuration ?
If OK for you, i will push a PR.

**Comment by Nyholm** [comment]
The lazy services are intentional because the sdk makes http requests when classes are instantiated. But I’m happy to remove the final keyword on the services.

**Comment by amenophis** [comment]
I speak about SDK classes that are final, you speak about those classes ? Or bundle ones ? You are a maintainer of auth0 SDK ?

**Comment by Nyholm** [comment]
Oh. I’m sorry. I just woke up :)

but I still believe I’m correct. We should open an issue/pr on the sdk to maker sure they are not final or that they don’t make the http request. (The latter allows us to remove “lazy”)

Please link to this issue.

**Comment by amenophis** [comment]
Ok will do a PR on the SDK directly !

**Comment by Nyholm** [comment]
The responses in https://github.com/auth0/auth0-PHP/issues/527 seams like we can remove "lazy" from this library. 

Do you want to make a PR?

**Comment by Nyholm** [comment]
Fixed by #47
