### ISSUE TITLE
Configuring Auth0 SdkConfiguration arguments

### ISSUE THREAD

**Issue by amenophis** [Happyr/auth0-bundle#43]
Hi @Nyholm,
The `auth0-php:@8.0.0-BETA1` fail to issue login link without defining `cookieSecret` parameter for `SdkConfiguration` (however defined as optionnal in code and documentation).
Configuration injected in the `SdkConfiguration` $oponfiguration argument is fixed the `ConfigurationProvider` service declaration.
How can we allow to define all available configuration:
  * Take a free array in the bundle configuration and let auth0 do the validation ?
  * Specify every SdkConfiguration constructor argument explicity in the bundle configuration to validate eveything is well configured before pass arguments to auth0 configuration ? 

What do you think ?

**Comment by Nyholm** [comment]
Thank you for this issue. 

Hm.. I like the simplicity of the first but that would imply that we dont validate the config until runtime (currently it is build time). 

I think we should add a few more "standard keys" and then fallback to a free array. I'll try to create a PR now.
