### ISSUE TITLE
No user_id in userinfo response

### ISSUE THREAD

**Issue by amenophis** [Happyr/auth0-bundle#45]
Hi @Nyholm,
Inside the `Auth0Authenticator::authenticate` method, there is a call to `Auth0\SDK\API\Authentication::userinfo` from access_token to retriev user informations.
In the case of social_login, the payload doesn't contain a user_id key, and the UserBadge can't be constructed with an Exception

**Comment by Nyholm** [comment]
Hm... How do you suggest to solve this?

**Comment by amenophis** [comment]
I tried with a classical login, and i do not have the user_id key ...

**Comment by Nyholm** [comment]
Oh.. I see the problem. 

What id do we have on such user?

https://auth0.com/docs/users/user-profile-structure

**Comment by Nyholm** [comment]
Maybe @evansims knows what unique identifier to use with users logging in with social media.

**Comment by clemherreman** [comment]
This is what we have with users logging in with social media (here with Google):

```
Happyr\Auth0Bundle\Model\UserInfo {#408 ▼
  -data: array:10 [▼
    "sub" => "google-oauth2|123423453456"
    "given_name" => "John"
    "family_name" => "Does"
    "nickname" => "john.does"
    "name" => "John Doe"
    "picture" => "https://lh3.googleusercontent.com/a/XXXXXXXX"
    "locale" => "fr"
    "updated_at" => "2021-08-06T15:32:00.660Z"
    "email" => "john.doe@foo.net"
    "email_verified" => true
  ]
}
```

`sub` looks like a good candidate?

**Comment by Nyholm** [comment]
Thank you. 

The same auth0 user that logs in with Facebook will have a different sub. So it is “too unique”. 

We had sub until 0.8.. but maybe I was wrong removing it. 

Why may make a difference between “user id” (which would be nullable) and “login identifier” (which is user is with fallback to sub). What do you think?
